#!/bin/bash
set -e

if [ -n "$CODESPACES" ]
then
  echo "Skip installing vscode extensions on codespaces"
  exit 0
fi

if ! command -v code >/dev/null
then
  echo "Install VS Code first!" >&2
  exit 1
fi

echo "List extensions:"
EXTENSIONS="$(code --list-extensions)"

echo "\t$EXTENSIONS"

for EXTENSION in $(cat $(dirname $0)/../vscode-extensions.txt)
do
  if echo "$EXTENSIONS" | grep -q "$EXTENSION"
  then
    echo "Extension '$EXTENSION' is already installed."
  else
    code --install-extension "$EXTENSION"
  fi
done
